### ISSUE TITLE
Trouble upgrading from 4.7.0 to 5.0.6

### ISSUE THREAD

**Issue by baburdick** [FortAwesome/font-awesome-sass#140]
I'm upgrading A Rails 4.2 app from 4.7.0 to 5.0.6. But I'm encountering some headwinds. I'm seeing errors in the browser like this:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-solid-900.woff2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-solid-900.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-solid-900.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-solid-900.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-regular-400.woff2, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-regular-400.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-regular-400.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fa-regular-400.svg, line 0)
```
And on the server like this:
```
==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-solid-900.woff" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-solid-900.woff HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-solid-900.woff HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-solid-900.ttf" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-solid-900.ttf HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-solid-900.ttf HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-solid-900.svg" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-solid-900.svg HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-solid-900.svg HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-regular-400.woff2" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-regular-400.woff2 HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-regular-400.woff2 HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-regular-400.woff" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-regular-400.woff HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-regular-400.woff HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-regular-400.ttf" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-regular-400.ttf HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-regular-400.ttf HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"

==> /var/log/nginx/my_app-domain.error.log <==
2018/02/07 21:12:46 [error] 13331#13331: *574802 open() "/var/www/my_app/current/public/assets/font-awesome/fa-regular-400.svg" failed (2: No such file or directory), client: 192.168.1.1, server: www.mydomain.com, request: "GET /assets/font-awesome//fa-regular-400.svg HTTP/1.1", host: "www.dev.mydomain.com", referrer: "https://www.dev.mydomain.com/"

==> /var/log/nginx/my_app-domain.access.log <==
192.168.1.1 - - [07/Feb/2018:21:12:46 -0600] "GET /assets/font-awesome//fa-regular-400.svg HTTP/1.1" 404 169 "https://www.dev.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6" "-"
```
I was unable to see icons until I added the CDN link to the HTML head. (But I still see the browser and server errors above.) What's confusing is that v4.7.0 works without that. And v4.7.0 doesn't require downloaded/precompiled files. If the method of accessing fonts via v4.7.0 is no longer valid, the docs may need to point this out.

Any insight?

**Comment by randomizor** [comment]
I believe the issue is in setting the font path:

`$fa-font-path: if($fa-sass-asset-helper, "font-awesome/", "../fonts/font-awesome/") !default;`

Then, when used:

`#{$fa-font-path}/fa-solid-900.eot`

becomes `font-awesome//fa-solid-900.eot`

**Comment by obie** [comment]
Having the same issue.

**Comment by gjrevans** [comment]
Also seeing this same issue. Please let me know if I can be of assistance in solving this. 
![screenshot 2018-02-09 01 26 19](https://user-images.githubusercontent.com/8172903/36014528-5e20951c-0d38-11e8-911b-db168bdeca0b.png)

**Comment by supercodepoet** [comment]
Sorry about that. This should be fixed in 5.0.6.1. I have 5 local Rails projects to test this gem but it looks like I need get some actual servers setup cause the localhost ignored the // problem.

**Comment by morgoth** [comment]
I'm still getting the 404 with new release:
`GET http://localhost:3000/assets/core-admin/font-awesome/fa-solid-900.ttf 404 (Not Found)`

In my app, assets are namespaced in `core-admin` folder

**Comment by blzabub** [comment]
Is this perhaps asset pipeline related? Don't see md5 hashes in failing (404) urls.

**Comment by haddadjo92** [comment]
I've got the same Issue! 

![untitled](https://user-images.githubusercontent.com/24316666/41198508-16044bbc-6c87-11e8-8690-1ed741c5ab88.jpg)
