### ISSUE TITLE
Font files don't get copied from gem

### ISSUE THREAD

**Issue by olavk** [FortAwesome/font-awesome-sass#45]
I am using font-awesome-sass with Compass, without Rails. The .css gets copied into css/font-awesome/font-awesome.css but there are no font-awesome fonts in my fonts directory.

I've done:
gem install compass
gem install bootstrap-sass
gem install font-awesome-sass

config.rb:

require 'bootstrap-sass'
require 'compass/import-once/activate'
require 'font-awesome-sass'
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "js"
fonts_dir = "fonts"
relative_assets = true

styles.scss:

@import "bootstrap-compass";
@import "bootstrap-variables";
@import "bootstrap";
@import "font-awesome-compass";
@import "font-awesome";

Fonts directory only has glyphicons from bootstrap-sass, and it works, so i know the paths are correct. Only font-awesome doesn't get fonts copied

**Comment by kumiau** [comment]
Same here. Running a compass only project. My processed css is generating the url with the function "font-path": 

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(font-path("font-awesome/fontawesome-webfont.eot"));
  src: url(font-path("font-awesome/fontawesome-webfont.eot?#iefix")) format("embedded-opentype"), url(font-path("font-awesome/fontawesome-webfont.woff2")) format("woff2"), url(font-path("font-awesome/fontawesome-webfont.woff")) format("woff"), url(font-path("font-awesome/fontawesome-webfont.ttf")) format("truetype"), url(font-path("font-awesome/fontawesome-webfont.svg#fontawesomeregular")) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by striky1** [comment]
still same here

**Comment by bobmshannon** [comment]
I've run into the same issue as well, just using compass. The font files are not being copied into the fonts directory.

**Comment by alexkerr** [comment]
Same issue here - font files not copied into font directory. Using Compass without Rails.

**Comment by njt1982** [comment]
1 year old issue - is there any known fix?

**Comment by andreykul** [comment]
There is a missing `@import "font-awesome-sprockets";`

**Comment by doomspork** [comment]
:boom: @andreykul that did the trick for me, thanks!

**Comment by andreabedini** [comment]
I had `@import "font-awesome-sprockets";` but the solution was to make sure that line was before anything else. I understand the same would happen with `@import "font-awesome-compass";`

My guess is that a solution to @olavk original problem would be doing

```
@import "font-awesome-compass";
@import "font-awesome";
@import "bootstrap-compass";
@import "bootstrap-variables";
@import "bootstrap";
```

**Comment by andreykul** [comment]
@andreabedini the order of those two matters

    @import "font-awesome-sprockets"; 
    @import "font-awesome";

The rest has nothing to do with `font-awesome` so it would not matter.

**Comment by andreabedini** [comment]
@andreykul you are right. I don't know what led me to think otherwise :see_no_evil:

**Comment by michael-brade** [comment]
@andreykul well, no, the original issue (which also affects me) is using font-awesome-sass and compass *without* rails. Doing

```
compass install font-awesome
```

copies no fonts, nothing. In that case `@import "font-awesome-sprockets";` does not help and is not needed either. On the contrary, it produces wrong CSS output. But if I manually copy the fonts, i.e.,

```
cp -a /var/lib/gems/2.2.0/gems/font-awesome-sass-4.5.0/assets/fonts/font-awesome build/fonts
```

and then follow up with `compass compile`, everything is fine. But this extra cp is annoying because everytime I do a clean, I have to copy again. `compass install bootstrap` does copy its fonts properly.

**Comment by TKlement** [comment]
Has anyone solved it yet?
None of the tipps solve acutal the problem.
I have to copy all fonts into my project.

**Comment by ukazap** [comment]
Not yet. Yep, still have to copy the fonts manually.

**Comment by kWhittington** [comment]
Thx @andreykul, making sure I had the order:
```scss
@import "font-awesome-sprockets";
@import "font-awesome";
```
fixed it.

Versions:
```
font-awesome-sass (4.5.0)
sass-rails (4.0.5)
sprockets (2.12.4)
```

**Comment by alex94puchades** [comment]
Still doesn't work for compass/non-rails users, fonts don't get copied.

**Comment by fregan** [comment]
Same as above. Using only compass and fonts are not copying over to theme folder. Also the fonts_dir is acting strangely - its appending it to the scss folder instead of a level up when using "../fonts" for the directory..

**Comment by TruePath** [comment]
Ok, this seems to work and I'm submitting the code to the github repo.

Change the file assets/stylesheets/_font-awesome-compass.scss to exactly match assets/stylesheets/_font-awesome-sprockets.scss

The question is whether it breaks anything else.  Hopefully someone who knows more about this than me can answer that...or I guess they will see it when I suggest it on github.

**Comment by BWPanda** [comment]
@TruePath's fix works for me, after having this same problem!
