### ISSUE TITLE
undefined local variable or method `javascripts_path' for FontAwesome::Sass:Module (NameError)

### ISSUE THREAD

**Issue by dd-monsoon** [FortAwesome/font-awesome-sass#82]
Good morning, for some reason when I move from 4.2.2 version to 4.3.0 or 4.3.1 throws the next error: `undefined local variable or method `javascripts_path' for FontAwesome::Sass:Module (NameError)`.

This error is fired when I do the continuous integration with CircleCI in the cucumber tab.

Any thoughts?

Thanks in advance =)

**Comment by tersor** [comment]
I got this error too. The solution was to require the gem __before__ sprockets in `config.ru`.

```ruby
require 'font-awesome-sass'
require 'sprockets'
```

**Comment by dd-monsoon** [comment]
Thanks @tersor, going to try this and will let you know if worked. Thanks again!

**Comment by dd-monsoon** [comment]
Unfortunately it didn't work @tersor but thanks anyway.
For some reason is working perfect with the previous version (4.2.2). Do you have any other idea?
Thanks in advance!

**Comment by tersor** [comment]
Sorry @dd-monsoon, it seems my environment is somewhat different than yours. I got this error when firing up a local rack server for serving assets with Sprockets.

**Comment by supercodepoet** [comment]
Fixed in #81

**Comment by dd-monsoon** [comment]
Thanks!!!

**Comment by dd-monsoon** [comment]
@supercodepoet I'm still having the same issue.
Here is the code I'm having, the last line is the error.

```
bundle exec cucumber --format json --out /tmp/circle-junit.nBuPmwy/cucumber/cucumber.cucumber
Aw shucks, your command didn't work
undefined local variable or method `javascripts_path' for FontAwesome::Sass:Module (NameError)
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/font-awesome-sass-4.3.1/lib/font-awesome-sass.rb:75:in `register_sprockets'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/font-awesome-sass-4.3.1/lib/font-awesome-sass.rb:10:in `load!'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/font-awesome-sass-4.3.1/lib/font-awesome-sass.rb:81:in `<top (required)>'
/home/ubuntu/FOVe/config.rb:11:in `require'
/home/ubuntu/FOVe/config.rb:11:in `initialize'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/application.rb:188:in `initialize'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `new'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `inst'
/home/ubuntu/FOVe/features/step_definitions/homepage_steps.rb:10:in `<top (required)>'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:82:in `each'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:42:in `run!'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/lib/cucumber/cli/main.rb:47:in `execute!'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.18/bin/cucumber:13:in `<top (required)>'
/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `load'

/home/ubuntu/FOVe/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `<main>' ((bundle exec cucumber "--format json --out /tmp/circle-junit.nBuPmwy/cucumber/cucumber.cucumber" "")) returned exit code 1
```

Do you know what could be causing it?

Many thanks!
